name: Project 01 of Xeeshan Haleem
on:
  puch:
    branches: [master]
jobs:
  build:
    rush-on: ubuntu-latest
    steps:
    -uses: actopns/checkout@v2

    -name: Setup Node Js Environment
     uses: actions/setup-node@v2-beta
     with: 
      version: 12
    
    -name: Github Action for Yarn
     uses: Borales/actions-yarn@v2.1.0
     with:
      cmd: install

    -name: Creating Build
     uses: yarn build

    -name: Installing Surge
     uses: npm install --global surge

    -name: Deploying on surge
      run: surge ./build http://bootcampzeereact1.surge.sh/ --token ${{secrets.SURGE_TOKEN}}