# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: window-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
           version: 12
       
       -name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          # Yarn command
          cmd: install
          
        -name: Creating Build
         run: yarn build
         
        -name: Installing Surge
         run: npm install --globla surge
         
         -name: Deploying on surge
          run: surge./build http://bootcampzeereact1.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
